name: Deploy CDK via OIDC

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable  

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-1"

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::241654666604:role/GitHub-Actions-CI-CD
          role-session-name: GitHubActionsSession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: CDK Synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cdk_subcommand: "synth"
          #working_dir: "src"

      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          actions_comment: true

      - name: CDK Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "stack1"
          cdk_args: "--require-approval never"
          actions_comment: false
