name: Deploy CDK via OIDC

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-west-1
      STACK_NAME: StreamerNotesLambdaStack

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: CDK Synth
        run: npx cdk synth

      - name: CDK Diff
        run: npx cdk diff

      - name: CDK Deploy
        run: npx cdk deploy

      